/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#484743',
        'primary-fixed-dim': '#d2bcff',
        'surface-dim': '#ded9d3',
        'secondary-container': '#e6e2dc',
        'on-tertiary-container': '#503d00',
        'inverse-surface': '#32302c',
        surface: '#fef9f1',
        'on-primary-fixed': '#25005a',
        'on-secondary-container': '#666460',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e7e2db',
        'on-tertiary-fixed': '#241a00',
        'on-primary-container': '#f8efff',
        primary: '#6343a4',
        'inverse-primary': '#d2bcff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f3ec',
        'primary-fixed': '#eaddff',
        'secondary-fixed': '#e6e2dc',
        'surface-tint': '#6b4bad',
        secondary: '#605e5a',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        tertiary: '#765b00',
        'tertiary-fixed': '#ffdf93',
        background: '#fef9f1',
        'tertiary-container': '#cca742',
        error: '#ba1a1a',
        'on-surface-variant': '#494551',
        'primary-container': '#7c5cbf',
        'secondary-fixed-dim': '#c9c6c0',
        'inverse-on-surface': '#f5f0e9',
        'on-tertiary-fixed-variant': '#594400',
        'surface-container-highest': '#e7e2db',
        'on-surface': '#1d1b17',
        'on-background': '#1d1b17',
        'outline-variant': '#cbc3d3',
        'on-primary-fixed-variant': '#533294',
        'tertiary-fixed-dim': '#e9c25a',
        'on-secondary-fixed': '#1c1c18',
        'surface-container-high': '#ece7e1',
        'on-error': '#ffffff',
        'surface-bright': '#fef9f1',
        'on-error-container': '#93000a',
        'surface-container': '#f2ede6',
        outline: '#7b7583',
        'severity-green': '#2BC48A',
        'severity-amber': '#FFB23E',
        'severity-coral': '#FF6B5E',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        md: '24px',
        sm: '12px',
        xl: '64px',
        gutter: '24px',
        margin: '32px',
        xs: '4px',
        lg: '40px',
      },
      fontFamily: {
        'metric-display': ['Space Mono', 'monospace'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'label-mono': ['Space Mono', 'monospace'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'metric-display': ['32px', { lineHeight: '1.0', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-mono': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        clay: '-8px -8px 24px rgba(255,255,255,0.8), 12px 12px 32px rgba(209,199,186,0.4)',
        'clay-sm': '-4px -4px 12px rgba(255,255,255,0.8), 6px 6px 16px rgba(209,199,186,0.4)',
        'clay-lg': '-12px -12px 32px rgba(255,255,255,0.9), 16px 16px 40px rgba(209,199,186,0.5)',
        'clay-inset': 'inset -4px -4px 8px rgba(255,255,255,0.8), inset 4px 4px 8px rgba(209,199,186,0.3)',
        'clay-plum': '-10px -10px 28px rgba(255,255,255,0.6), 14px 14px 36px rgba(99,67,164,0.3)',
      },
    },
  },
  plugins: [],
}
